# ================================================
# FILE: constants/statuses.py
# ================================================

SIGNUP_STATUS_SIGN = "sign"
SIGNUP_STATUS_BENCH = "bench"
SIGNUP_STATUS_LATE = "late"
SIGNUP_STATUS_TENTATIVE = "tentative"
SIGNUP_STATUS_ABSENCE = "absence"

SIGNUP_STATUSES = [
    SIGNUP_STATUS_SIGN,
    SIGNUP_STATUS_BENCH,
    SIGNUP_STATUS_LATE,
    SIGNUP_STATUS_TENTATIVE,
    SIGNUP_STATUS_ABSENCE,
]


ATTENDANCE_STATUS_ATTENDING = "attending"
ATTENDANCE_STATUS_BENCHED = "benched"
ATTENDANCE_STATUS_LATE = "late"
ATTENDANCE_STATUS_TENTATIVE = "tentative"
ATTENDANCE_STATUS_ABSENT = "absent"
ATTENDANCE_STATUS_NO_SIGN = "no_sign"

ATTENDANCE_STATUSES = [
    ATTENDANCE_STATUS_ATTENDING,
    ATTENDANCE_STATUS_BENCHED,
    ATTENDANCE_STATUS_LATE,
    ATTENDANCE_STATUS_TENTATIVE,
    ATTENDANCE_STATUS_ABSENT,
    ATTENDANCE_STATUS_NO_SIGN,
]


STATUS_LABELS = {
    SIGNUP_STATUS_SIGN: "Sign",
    SIGNUP_STATUS_BENCH: "Bench",
    SIGNUP_STATUS_LATE: "Late",
    SIGNUP_STATUS_TENTATIVE: "Tentative",
    SIGNUP_STATUS_ABSENCE: "Absence",

    ATTENDANCE_STATUS_ATTENDING: "Attending",
    ATTENDANCE_STATUS_BENCHED: "Benched",
    ATTENDANCE_STATUS_ABSENT: "Absent",
    ATTENDANCE_STATUS_NO_SIGN: "No Sign",
}


STATUS_EMOJIS = {
    SIGNUP_STATUS_SIGN: "✅",
    SIGNUP_STATUS_BENCH: "🪑",
    SIGNUP_STATUS_LATE: "⏰",
    SIGNUP_STATUS_TENTATIVE: "❔",
    SIGNUP_STATUS_ABSENCE: "❌",

    ATTENDANCE_STATUS_ATTENDING: "✅",
    ATTENDANCE_STATUS_BENCHED: "🪑",
    ATTENDANCE_STATUS_ABSENT: "❌",
    ATTENDANCE_STATUS_NO_SIGN: "⚫",
}