# Core generic timings
ERROR_MESSAGE_AUTO_DELETE_SECONDS = 10
SHORT_CONFIRMATION_AUTO_DELETE_SECONDS = 10

# Backward compatibility for older imports
SHORT_CONFIRMATION_DELETE_SECONDS = SHORT_CONFIRMATION_AUTO_DELETE_SECONDS

# Panels / menus
SIGNUP_OPTIONS_AUTO_DELETE_SECONDS = 30
CHARACTER_MENU_AUTO_DELETE_SECONDS = 30
RAID_CONTROL_AUTO_DELETE_SECONDS = 60
SLASH_PANEL_AUTO_DELETE_SECONDS = 60

# Slash-command one-off replies
SLASH_COMMAND_RESPONSE_AUTO_DELETE_SECONDS = 10

# Special cases
ATTENDANCE_REPORT_AUTO_DELETE_SECONDS = 45