# Core generic timings
ERROR_MESSAGE_AUTO_DELETE_SECONDS = 15
SHORT_CONFIRMATION_AUTO_DELETE_SECONDS = 12

# Panels / menus
SIGNUP_OPTIONS_AUTO_DELETE_SECONDS = 60
CHARACTER_MENU_AUTO_DELETE_SECONDS = 60
RAID_CONTROL_AUTO_DELETE_SECONDS = 60
SLASH_PANEL_AUTO_DELETE_SECONDS = 60

# Slash-command one-off replies
SLASH_COMMAND_RESPONSE_AUTO_DELETE_SECONDS = 20

# Special cases
ATTENDANCE_REPORT_AUTO_DELETE_SECONDS = 45